version: '3.3'
services:
  db:
    container_name: postgres_blog_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres_blog:/data/postgres
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_blog_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_blog:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
  blog-backend:
    container_name: blog-backend
    image: blog-backend
    environment:
      HOST: 127.0.0.1,
      PORT: 4000,
      DB_HOST: db

    volumes:
      - ./uploads:/app/uploads
    ports:
      - "4000:4000"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres_blog:
  pgadmin_blog: